/**
 * integration.smoke.test.ts — ONE live MCP-client smoke against production.
 *
 * Spawns the built dist/index.js over stdio with a real MCP client
 * (@modelcontextprotocol/sdk/client) and the demo key, then:
 *   1. tools/list           -> asserts the 3 tools (protocol only, no API call)
 *   2. list_templates tool  -> live GET /v1/templates (public, unmetered)
 *   3. render_pdf tool      -> ONE live metered render (demo tier 3/min, 50/mo)
 *
 * Per plan hard rule: max 1-2 live API calls — exactly one metered render.
 * Raw HTML is used for the render (NOT template_id): production currently has
 * a known 500 render bug on template renders (pre-existing, under
 * investigation) — same precedent as the JS/Python SDK smokes.
 *
 * Demo key: PUBLIC BY DESIGN (D-52, 05-01-SUMMARY.md). Override with
 * DOCJET_DEMO_KEY env. Gate: only runs when DOCJET_SMOKE=true — normal
 * `npm test` skips this file's bodies entirely.
 *
 * Requires `npm run build` first (spawns dist/index.js).
 */
import { fileURLToPath } from 'node:url';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import {
  StdioClientTransport,
  getDefaultEnvironment,
} from '@modelcontextprotocol/sdk/client/stdio.js';

// Demo key: PUBLIC BY DESIGN (D-52, 05-01-SUMMARY.md)
const DEMO_KEY =
  process.env.DOCJET_DEMO_KEY ??
  'binfra_9afb57dbb6478c441ad101129fca65847f5745403f9d718b3de6d934c9b63f88';

const SMOKE_ENABLED = process.env.DOCJET_SMOKE === 'true';

const SERVER_PATH = fileURLToPath(new URL('../../dist/index.js', import.meta.url));

type TextContent = Array<{ type: string; text: string }>;

describe('docjet-mcp live MCP-client smoke (stdio)', () => {
  let client: Client | undefined;

  beforeAll(async () => {
    if (!SMOKE_ENABLED) return;
    client = new Client({ name: 'docjet-mcp-smoke', version: '1.0.0' });
    const transport = new StdioClientTransport({
      command: process.execPath, // current node binary — robust on Windows
      args: [SERVER_PATH],
      env: { ...getDefaultEnvironment(), DOCJET_API_KEY: DEMO_KEY },
    });
    await client.connect(transport);
  }, 30_000);

  afterAll(async () => {
    await client?.close();
  });

  it.skipIf(!SMOKE_ENABLED)('tools/list returns the 3 tools', async () => {
    const { tools } = await client!.listTools();
    const names = tools.map((t) => t.name).sort();
    expect(names).toEqual(['list_templates', 'render_image', 'render_pdf']);
    // every tool ships an input schema
    for (const tool of tools) {
      expect(tool.inputSchema).toBeDefined();
    }
  });

  it.skipIf(!SMOKE_ENABLED)(
    'list_templates returns the live template array',
    async () => {
      const result = await client!.callTool({ name: 'list_templates', arguments: {} });
      const content = result.content as TextContent;
      const templates = JSON.parse(content[0].text) as Array<{ id: string }>;
      expect(Array.isArray(templates)).toBe(true);
      expect(templates.length).toBeGreaterThan(0);
      expect(templates[0]).toHaveProperty('id');
    },
    30_000,
  );

  it.skipIf(!SMOKE_ENABLED)(
    'render_pdf (raw HTML) returns a signed render URL from production',
    async () => {
      const result = await client!.callTool({
        name: 'render_pdf',
        arguments: {
          html: '<h1>docjet-mcp smoke</h1><p>Generated by the docjet-mcp integration test.</p>',
          data: {},
        },
      });
      expect(result.isError ?? false).toBe(false);
      const content = result.content as TextContent;
      expect(content[0].text).toMatch(/^https?:\/\//);
    },
    60_000,
  );
});
